import { createFileRoute, Link } from '@tanstack/react-router'
import { useState } from "react";
import { ChevronRight, LayoutGrid, List } from "lucide-react";
import {
  Sidebar,
  NewBuildUnitButton,
  DisplayButton,
  FilterButton,
  BuildUnitsTable,
  BuildUnitsGrid,
  BuildUnitsFilterPanel,
  applyBuildUnitFilters,
  EMPTY_BUILD_UNIT_FILTERS,
  RoutePendingComponent,
} from "../../../../components/buildInlime";
import { useProjectBuildUnits } from "../../../../hooks/use-project-build-units";

export const Route = createFileRoute('/_authenticated/projects/$projectId/')({
  component: ProjectRoute,
  pendingComponent: RoutePendingComponent,
})

function ProjectRoute() {
  const { projectId } = Route.useParams()
  const { projectName, buildUnits, pendingIds, addPending, removePending, onTrpcComplete, onBuildUnitClick } =
    useProjectBuildUnits(projectId)

  // Toggle between the tabular view (default) and a thumbnail/card grid,
  // driven by the "Display" toolbar button.
  const [viewMode, setViewMode] = useState<"table" | "grid">("table")

  // "Filter" toolbar button toggles a side panel; applied filter values narrow
  // the rows shown in the table/grid on the left.
  const [filterOpen, setFilterOpen] = useState(false)
  const [filters, setFilters] = useState(EMPTY_BUILD_UNIT_FILTERS)
  const visibleBuildUnits = applyBuildUnitFilters(buildUnits, filters)

  return (
    <div className="flex h-screen bg-white font-['Instrument_Sans',sans-serif]">
      {/* Sidebar */}
      <Sidebar projectId={projectId} />

      {/* Main content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Header */}
        <header className="h-14 bg-white border-b border-card-border flex items-center justify-between px-6">
          <div className="flex items-center gap-2">
            <Link
              to="/projects"
              className="font-['Instrument_Sans',sans-serif] font-medium text-[14px] text-muted-foreground hover:text-foreground"
              style={{ fontVariationSettings: "'wdth' 100" }}
            >
              Projects
            </Link>
            <ChevronRight className="w-4 h-4 text-muted-foreground" />
            <span
              className="font-['Instrument_Sans',sans-serif] font-semibold text-[18px] text-foreground"
              style={{ fontVariationSettings: "'wdth' 100" }}
            >
              {projectName}
            </span>
          </div>
          <NewBuildUnitButton addPending={addPending} removePending={removePending} onTrpcComplete={onTrpcComplete} />
        </header>

        {/* Toolbar */}
        <div className="bg-white border-b border-card-border px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <button
              className="font-['Instrument_Sans',sans-serif] font-medium text-[14px] text-foreground pb-1 border-b-2 border-primary"
              style={{ fontVariationSettings: "'wdth' 100" }}
            >
              All Build Units
            </button>
            {/*
              FUTURE WORK: "New View" is a non-functional placeholder, hidden
              until built. Intended behaviour:
                1) Let users view the work on build units through different
                   metrics and dimensions (custom saved views over the table).
                2) Views will potentially be generated by AI based on the user's
                   inputs, using the build unit data already in the DB.

              <button
                className="font-['Instrument_Sans',sans-serif] font-medium text-[14px] text-muted-foreground hover:text-foreground flex items-center gap-1 transition-colors"
                style={{ fontVariationSettings: "'wdth' 100" }}
              >
                <Plus className="w-3 h-3" />
                New View
              </button>
            */}
          </div>
          <div className="flex items-center gap-2">
            <DisplayButton
              onClick={() => setViewMode((m) => (m === "table" ? "grid" : "table"))}
              icon={viewMode === "table" ? LayoutGrid : List}
              label={viewMode === "table" ? "Thumbnails" : "Table"}
            />
            <FilterButton onClick={() => setFilterOpen((o) => !o)} active={filterOpen} />
          </div>
        </div>

        {/* Content: build units on the left, filter side panel (when open) on the
            right — both sit below the toolbar and share the remaining height. */}
        <div className="flex flex-1 overflow-hidden">
          {viewMode === "table" ? (
            <BuildUnitsTable buildUnits={visibleBuildUnits} onBuildUnitClick={onBuildUnitClick} pendingIds={pendingIds} />
          ) : (
            <BuildUnitsGrid buildUnits={visibleBuildUnits} onBuildUnitClick={onBuildUnitClick} pendingIds={pendingIds} />
          )}
          {filterOpen && (
            <BuildUnitsFilterPanel
              initialFilters={filters}
              onApply={setFilters}
              onClose={() => setFilterOpen(false)}
            />
          )}
        </div>
      </div>
    </div>
  );
}
