/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiTeamsRouteImport } from './routes/api/teams'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiResourcesRouteImport } from './routes/api/resources'
import { Route as ApiReadsRouteImport } from './routes/api/reads'
import { Route as ApiPropertiesRouteImport } from './routes/api/properties'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiMembershipsRouteImport } from './routes/api/memberships'
import { Route as ApiChannelsRouteImport } from './routes/api/channels'
import { Route as ApiChannelMembersRouteImport } from './routes/api/channel-members'
import { Route as ApiBuildunitsRouteImport } from './routes/api/buildunits'
import { Route as AuthenticatedMyTasksRouteImport } from './routes/_authenticated/my-tasks'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiResourcesUploadRouteImport } from './routes/api/resources/upload'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects/$projectId/index'
import { Route as ApiResourcesResourceIdFileRouteImport } from './routes/api/resources/$resourceId/file'
import { Route as AuthenticatedProjectsProjectIdBuildUnitNameRouteImport } from './routes/_authenticated/projects/$projectId/$buildUnitName'
import { Route as AuthenticatedProjectsProjectIdBuildUnitNameIndexRouteImport } from './routes/_authenticated/projects/$projectId/$buildUnitName/index'
import { Route as AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteImport } from './routes/_authenticated/projects/$projectId/$buildUnitName/$channelName'
import { Route as AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRouteImport } from './routes/_authenticated/projects/$projectId/$buildUnitName/$channelName/index'
import { Route as AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRouteImport } from './routes/_authenticated/projects/$projectId/$buildUnitName/$channelName/$taskName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamsRoute = ApiTeamsRouteImport.update({
  id: '/api/teams',
  path: '/api/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesRoute = ApiResourcesRouteImport.update({
  id: '/api/resources',
  path: '/api/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadsRoute = ApiReadsRouteImport.update({
  id: '/api/reads',
  path: '/api/reads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPropertiesRoute = ApiPropertiesRouteImport.update({
  id: '/api/properties',
  path: '/api/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembershipsRoute = ApiMembershipsRouteImport.update({
  id: '/api/memberships',
  path: '/api/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsRoute = ApiChannelsRouteImport.update({
  id: '/api/channels',
  path: '/api/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelMembersRoute = ApiChannelMembersRouteImport.update({
  id: '/api/channel-members',
  path: '/api/channel-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildunitsRoute = ApiBuildunitsRouteImport.update({
  id: '/api/buildunits',
  path: '/api/buildunits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyTasksRoute = AuthenticatedMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResourcesUploadRoute = ApiResourcesUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiResourcesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const ApiResourcesResourceIdFileRoute =
  ApiResourcesResourceIdFileRouteImport.update({
    id: '/$resourceId/file',
    path: '/$resourceId/file',
    getParentRoute: () => ApiResourcesRoute,
  } as any)
const AuthenticatedProjectsProjectIdBuildUnitNameRoute =
  AuthenticatedProjectsProjectIdBuildUnitNameRouteImport.update({
    id: '/$buildUnitName',
    path: '/$buildUnitName',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute =
  AuthenticatedProjectsProjectIdBuildUnitNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdBuildUnitNameRoute,
  } as any)
const AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute =
  AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteImport.update({
    id: '/$channelName',
    path: '/$channelName',
    getParentRoute: () => AuthenticatedProjectsProjectIdBuildUnitNameRoute,
  } as any)
const AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute =
  AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute,
    } as any,
  )
const AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute =
  AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRouteImport.update(
    {
      id: '/$taskName',
      path: '/$taskName',
      getParentRoute: () =>
        AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/my-tasks': typeof AuthenticatedMyTasksRoute
  '/api/buildunits': typeof ApiBuildunitsRoute
  '/api/channel-members': typeof ApiChannelMembersRoute
  '/api/channels': typeof ApiChannelsRoute
  '/api/memberships': typeof ApiMembershipsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/reads': typeof ApiReadsRoute
  '/api/resources': typeof ApiResourcesRouteWithChildren
  '/api/tasks': typeof ApiTasksRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/users': typeof ApiUsersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/resources/upload': typeof ApiResourcesUploadRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/$buildUnitName': typeof AuthenticatedProjectsProjectIdBuildUnitNameRouteWithChildren
  '/api/resources/$resourceId/file': typeof ApiResourcesResourceIdFileRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/$buildUnitName/$channelName': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteWithChildren
  '/projects/$projectId/$buildUnitName/': typeof AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute
  '/projects/$projectId/$buildUnitName/$channelName/$taskName': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute
  '/projects/$projectId/$buildUnitName/$channelName/': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/my-tasks': typeof AuthenticatedMyTasksRoute
  '/api/buildunits': typeof ApiBuildunitsRoute
  '/api/channel-members': typeof ApiChannelMembersRoute
  '/api/channels': typeof ApiChannelsRoute
  '/api/memberships': typeof ApiMembershipsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/reads': typeof ApiReadsRoute
  '/api/resources': typeof ApiResourcesRouteWithChildren
  '/api/tasks': typeof ApiTasksRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/resources/upload': typeof ApiResourcesUploadRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/api/resources/$resourceId/file': typeof ApiResourcesResourceIdFileRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/projects/$projectId/$buildUnitName': typeof AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute
  '/projects/$projectId/$buildUnitName/$channelName/$taskName': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute
  '/projects/$projectId/$buildUnitName/$channelName': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/my-tasks': typeof AuthenticatedMyTasksRoute
  '/api/buildunits': typeof ApiBuildunitsRoute
  '/api/channel-members': typeof ApiChannelMembersRoute
  '/api/channels': typeof ApiChannelsRoute
  '/api/memberships': typeof ApiMembershipsRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/properties': typeof ApiPropertiesRoute
  '/api/reads': typeof ApiReadsRoute
  '/api/resources': typeof ApiResourcesRouteWithChildren
  '/api/tasks': typeof ApiTasksRoute
  '/api/teams': typeof ApiTeamsRoute
  '/api/users': typeof ApiUsersRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/resources/upload': typeof ApiResourcesUploadRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/$buildUnitName': typeof AuthenticatedProjectsProjectIdBuildUnitNameRouteWithChildren
  '/api/resources/$resourceId/file': typeof ApiResourcesResourceIdFileRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
  '/_authenticated/projects/$projectId/$buildUnitName/$channelName': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteWithChildren
  '/_authenticated/projects/$projectId/$buildUnitName/': typeof AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute
  '/_authenticated/projects/$projectId/$buildUnitName/$channelName/$taskName': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute
  '/_authenticated/projects/$projectId/$buildUnitName/$channelName/': typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inbox'
    | '/my-tasks'
    | '/api/buildunits'
    | '/api/channel-members'
    | '/api/channels'
    | '/api/memberships'
    | '/api/messages'
    | '/api/projects'
    | '/api/properties'
    | '/api/reads'
    | '/api/resources'
    | '/api/tasks'
    | '/api/teams'
    | '/api/users'
    | '/projects/$projectId'
    | '/api/auth/$'
    | '/api/resources/upload'
    | '/api/trpc/$'
    | '/projects/'
    | '/projects/$projectId/$buildUnitName'
    | '/api/resources/$resourceId/file'
    | '/projects/$projectId/'
    | '/projects/$projectId/$buildUnitName/$channelName'
    | '/projects/$projectId/$buildUnitName/'
    | '/projects/$projectId/$buildUnitName/$channelName/$taskName'
    | '/projects/$projectId/$buildUnitName/$channelName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/inbox'
    | '/my-tasks'
    | '/api/buildunits'
    | '/api/channel-members'
    | '/api/channels'
    | '/api/memberships'
    | '/api/messages'
    | '/api/projects'
    | '/api/properties'
    | '/api/reads'
    | '/api/resources'
    | '/api/tasks'
    | '/api/teams'
    | '/api/users'
    | '/api/auth/$'
    | '/api/resources/upload'
    | '/api/trpc/$'
    | '/projects'
    | '/api/resources/$resourceId/file'
    | '/projects/$projectId'
    | '/projects/$projectId/$buildUnitName'
    | '/projects/$projectId/$buildUnitName/$channelName/$taskName'
    | '/projects/$projectId/$buildUnitName/$channelName'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/inbox'
    | '/_authenticated/my-tasks'
    | '/api/buildunits'
    | '/api/channel-members'
    | '/api/channels'
    | '/api/memberships'
    | '/api/messages'
    | '/api/projects'
    | '/api/properties'
    | '/api/reads'
    | '/api/resources'
    | '/api/tasks'
    | '/api/teams'
    | '/api/users'
    | '/_authenticated/projects/$projectId'
    | '/api/auth/$'
    | '/api/resources/upload'
    | '/api/trpc/$'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/$buildUnitName'
    | '/api/resources/$resourceId/file'
    | '/_authenticated/projects/$projectId/'
    | '/_authenticated/projects/$projectId/$buildUnitName/$channelName'
    | '/_authenticated/projects/$projectId/$buildUnitName/'
    | '/_authenticated/projects/$projectId/$buildUnitName/$channelName/$taskName'
    | '/_authenticated/projects/$projectId/$buildUnitName/$channelName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiBuildunitsRoute: typeof ApiBuildunitsRoute
  ApiChannelMembersRoute: typeof ApiChannelMembersRoute
  ApiChannelsRoute: typeof ApiChannelsRoute
  ApiMembershipsRoute: typeof ApiMembershipsRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiPropertiesRoute: typeof ApiPropertiesRoute
  ApiReadsRoute: typeof ApiReadsRoute
  ApiResourcesRoute: typeof ApiResourcesRouteWithChildren
  ApiTasksRoute: typeof ApiTasksRoute
  ApiTeamsRoute: typeof ApiTeamsRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teams': {
      id: '/api/teams'
      path: '/api/teams'
      fullPath: '/api/teams'
      preLoaderRoute: typeof ApiTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources': {
      id: '/api/resources'
      path: '/api/resources'
      fullPath: '/api/resources'
      preLoaderRoute: typeof ApiResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reads': {
      id: '/api/reads'
      path: '/api/reads'
      fullPath: '/api/reads'
      preLoaderRoute: typeof ApiReadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/properties': {
      id: '/api/properties'
      path: '/api/properties'
      fullPath: '/api/properties'
      preLoaderRoute: typeof ApiPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/memberships': {
      id: '/api/memberships'
      path: '/api/memberships'
      fullPath: '/api/memberships'
      preLoaderRoute: typeof ApiMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels': {
      id: '/api/channels'
      path: '/api/channels'
      fullPath: '/api/channels'
      preLoaderRoute: typeof ApiChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channel-members': {
      id: '/api/channel-members'
      path: '/api/channel-members'
      fullPath: '/api/channel-members'
      preLoaderRoute: typeof ApiChannelMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/buildunits': {
      id: '/api/buildunits'
      path: '/api/buildunits'
      fullPath: '/api/buildunits'
      preLoaderRoute: typeof ApiBuildunitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-tasks': {
      id: '/_authenticated/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AuthenticatedMyTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resources/upload': {
      id: '/api/resources/upload'
      path: '/upload'
      fullPath: '/api/resources/upload'
      preLoaderRoute: typeof ApiResourcesUploadRouteImport
      parentRoute: typeof ApiResourcesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/api/resources/$resourceId/file': {
      id: '/api/resources/$resourceId/file'
      path: '/$resourceId/file'
      fullPath: '/api/resources/$resourceId/file'
      preLoaderRoute: typeof ApiResourcesResourceIdFileRouteImport
      parentRoute: typeof ApiResourcesRoute
    }
    '/_authenticated/projects/$projectId/$buildUnitName': {
      id: '/_authenticated/projects/$projectId/$buildUnitName'
      path: '/$buildUnitName'
      fullPath: '/projects/$projectId/$buildUnitName'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/$buildUnitName/': {
      id: '/_authenticated/projects/$projectId/$buildUnitName/'
      path: '/'
      fullPath: '/projects/$projectId/$buildUnitName/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameRoute
    }
    '/_authenticated/projects/$projectId/$buildUnitName/$channelName': {
      id: '/_authenticated/projects/$projectId/$buildUnitName/$channelName'
      path: '/$channelName'
      fullPath: '/projects/$projectId/$buildUnitName/$channelName'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameRoute
    }
    '/_authenticated/projects/$projectId/$buildUnitName/$channelName/': {
      id: '/_authenticated/projects/$projectId/$buildUnitName/$channelName/'
      path: '/'
      fullPath: '/projects/$projectId/$buildUnitName/$channelName/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute
    }
    '/_authenticated/projects/$projectId/$buildUnitName/$channelName/$taskName': {
      id: '/_authenticated/projects/$projectId/$buildUnitName/$channelName/$taskName'
      path: '/$taskName'
      fullPath: '/projects/$projectId/$buildUnitName/$channelName/$taskName'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute
    }
  }
}

interface AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteChildren {
  AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute
  AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute
}

const AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteChildren: AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteChildren =
  {
    AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute:
      AuthenticatedProjectsProjectIdBuildUnitNameChannelNameTaskNameRoute,
    AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute:
      AuthenticatedProjectsProjectIdBuildUnitNameChannelNameIndexRoute,
  }

const AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteWithChildren =
  AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute._addFileChildren(
    AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteChildren,
  )

interface AuthenticatedProjectsProjectIdBuildUnitNameRouteChildren {
  AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteWithChildren
  AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute
}

const AuthenticatedProjectsProjectIdBuildUnitNameRouteChildren: AuthenticatedProjectsProjectIdBuildUnitNameRouteChildren =
  {
    AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRoute:
      AuthenticatedProjectsProjectIdBuildUnitNameChannelNameRouteWithChildren,
    AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute:
      AuthenticatedProjectsProjectIdBuildUnitNameIndexRoute,
  }

const AuthenticatedProjectsProjectIdBuildUnitNameRouteWithChildren =
  AuthenticatedProjectsProjectIdBuildUnitNameRoute._addFileChildren(
    AuthenticatedProjectsProjectIdBuildUnitNameRouteChildren,
  )

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdBuildUnitNameRoute: typeof AuthenticatedProjectsProjectIdBuildUnitNameRouteWithChildren
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdBuildUnitNameRoute:
      AuthenticatedProjectsProjectIdBuildUnitNameRouteWithChildren,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedMyTasksRoute: typeof AuthenticatedMyTasksRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedMyTasksRoute: AuthenticatedMyTasksRoute,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiResourcesRouteChildren {
  ApiResourcesUploadRoute: typeof ApiResourcesUploadRoute
  ApiResourcesResourceIdFileRoute: typeof ApiResourcesResourceIdFileRoute
}

const ApiResourcesRouteChildren: ApiResourcesRouteChildren = {
  ApiResourcesUploadRoute: ApiResourcesUploadRoute,
  ApiResourcesResourceIdFileRoute: ApiResourcesResourceIdFileRoute,
}

const ApiResourcesRouteWithChildren = ApiResourcesRoute._addFileChildren(
  ApiResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiBuildunitsRoute: ApiBuildunitsRoute,
  ApiChannelMembersRoute: ApiChannelMembersRoute,
  ApiChannelsRoute: ApiChannelsRoute,
  ApiMembershipsRoute: ApiMembershipsRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiPropertiesRoute: ApiPropertiesRoute,
  ApiReadsRoute: ApiReadsRoute,
  ApiResourcesRoute: ApiResourcesRouteWithChildren,
  ApiTasksRoute: ApiTasksRoute,
  ApiTeamsRoute: ApiTeamsRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
